# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "minirust"
version = "0.1.0"
edition = "2018"

[profile.release]
lto = true

[dependencies]
handlebars = "4.1.1"
lettre = { version = "0.10.0-rc.3", features = ["rustls-tls"] }
openssl = { version = "0.10.34", features = ["vendored"] }
which = "4.1.0"
